<a href="https://colab.research.google.com/github/sohomghosh/CEPN/blob/main/FinCausal2022_submisssion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here are general scenarios to keep in mind (and avoid) while submitting:

*   Empty "Cause" and/or "Effect" columns
*   Uneven (longer/shorter) submissions
*   Random fillings (i.e., filling the "Cause" and/or "Effect" columns with chunks that do not appear in the corresponding "Text" column)


Make sure your zip file submission replicates the exact format provided in the sample file on the *Learn the Details* -> *Evaluation* tab of the Codalab competition.
The name of the zip file is irrelevant, but the name of the file inside the zip should be task2.csv

Wether you make one or multiple submissions, please choose the one you want to display on the leaderboard cliking on the *Push to Leaderboar* button that will appear once your sumbission has STATUS: Finishedhere can be up to 1 minute latency between status changing from *Submitted* to *Finished*

You can submit up to 100 times but only one result can be pushed to the leaderboard

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

In [ ]:
dummy_submission = pd.read_csv('task2_sample.csv', sep = ';')

In [ ]:
dummy_submission

,Index,Text,Cause,Effect
0,291.00004,The Israel Tax Authority claims that when a c...,The Israel Tax Authority claims that when a c...,The Israel Tax Authority claims that when a c...
1,291.00005,"Because Oshrad is a privately held business, ...","Because Oshrad is a privately held business, ...","Because Oshrad is a privately held business, ..."
2,291.00006,"Instead, the company reported itself as a fam...","Instead, the company reported itself as a fam...","Instead, the company reported itself as a fam..."
3,292.00007,"On Tuesday, repo loan rates more than tripled...","On Tuesday, repo loan rates more than tripled...","On Tuesday, repo loan rates more than tripled..."
4,293.00008,"Approximately 144 jurisdictions use IFRS, as ...","Approximately 144 jurisdictions use IFRS, as ...","Approximately 144 jurisdictions use IFRS, as ..."
...,...,...,...,...
928,291,"On December 19, 2019, proceeds from the UKWG a...","On December 19, 2019, proceeds from the UKWG a...","On December 19, 2019, proceeds from the UKWG a..."
929,292,"At December 31, 2020, there was $7 million of ...","At December 31, 2020, there was $7 million of ...","At December 31, 2020, there was $7 million of ..."
930,293,"In addition, as of March 31, 2018, we adopted ...","In addition, as of March 31, 2018, we adopted ...","In addition, as of March 31, 2018, we adopted ..."
931,294,The deferred portion of the state and local ta...,The deferred portion of the state and local ta...,The deferred portion of the state and local ta...
932,295,The deferred portion of the foreign taxes incl...,The deferred portion of the foreign taxes incl...,The deferred portion of the foreign taxes incl...

In [ ]:
file = 'FinCausal-2022_output - best_so_far_all_effect_treated.csv'
#'FinCausal-2022_output - cause_effect_ensemble.csv'
#'FinCausal-2022_output - Sheet1.csv'
#'task2_fincausal2020bestmodel_scoredon_eval2022 (copy).csv'
#'pred_finbert_no_pos_test_output.csv'
#'pred_bert_sec_no_pos_test_output.csv'
#'bert_till2022_trained_output_test_no_pos.csv'
#'pred_fcausal2020_ex_no_pos_test_output.csv'
#'bert_till2022_trained_output_test.csv'
#'task2_fincausal2020bestmodel_scoredon_eval2022.csv'
#'task2_train2021_eval2022.csv'
#'task2_train2020_eval2022.csv'
#'large_task2_traintill2022all_eval2022.csv'
#'large_task2_train2021_eval2022.csv'
#'large_task2_train2020_eval2022.csv'
#'bert_sec_task2_traintill2022all_eval2022'

In [ ]:
actual_submission = pd.read_csv(file)#, sep = ';')

In [ ]:
actual_submission

,Index,Text,Cause,Effect
0,291.00004,The Israel Tax Authority claims that when a co...,The Israel Tax Authority claims that when a co...,they should have paid 4.3 million shekels in tax.
1,291.00005,"Because Oshrad is a privately held business, i...",Because Oshrad is a privately held business,it was liable for a 26.3% company tax on the s...
2,291.00006,"Instead, the company reported itself as a fami...","Instead, the company reported itself as a fami...",is liable to a single 32% tax.
3,292.00007,"On Tuesday, repo loan rates more than tripled ...","On Tuesday, repo loan rates more than tripled","the supply of funds to the banking system, and..."
4,293.00008,"Approximately 144 jurisdictions use IFRS, as i...",it's required for public firms based in South ...,Approximately 144 jurisdictions use IFRS
...,...,...,...,...
928,291,"On December 19, 2019, proceeds from the UKWG a...","On December 19, 2019, proceeds from the UKWG a...","In connection with this early retirement, we i..."
929,292,"At December 31, 2020, there was $7 million of ...",unvested restricted stock units such units had...,"At December 31, 2020, there was $7 million of ..."
930,293,"In addition, as of March 31, 2018, we adopted ...","In addition, as of March 31, 2018, we adopted ...","As a result of the adoption, we reclassified $..."
931,294,The deferred portion of the state and local ta...,changes in valuation allowances against state ...,The deferred portion of the state and local ta...
932,295,The deferred portion of the foreign taxes incl...,a change in the valuation allowances against f...,The deferred portion of the foreign taxes incl...

In [ ]:
actual_submission.columns = dummy_submission.columns

In [ ]:
actual_submission.columns

Index(['Index', ' Text', 'Cause', 'Effect'], dtype='object')

In [ ]:
del actual_submission['Index']
del actual_submission[' Text']

actual_submission['Index'] = dummy_submission['Index']
actual_submission[' Text'] = dummy_submission[' Text']

In [ ]:
actual_submission

,Cause,Effect,Index,Text
0,The Israel Tax Authority claims that when a co...,they should have paid 4.3 million shekels in tax.,291.00004,The Israel Tax Authority claims that when a c...
1,Because Oshrad is a privately held business,it was liable for a 26.3% company tax on the s...,291.00005,"Because Oshrad is a privately held business, ..."
2,"Instead, the company reported itself as a fami...",is liable to a single 32% tax.,291.00006,"Instead, the company reported itself as a fam..."
3,"On Tuesday, repo loan rates more than tripled","the supply of funds to the banking system, and...",292.00007,"On Tuesday, repo loan rates more than tripled..."
4,it's required for public firms based in South ...,Approximately 144 jurisdictions use IFRS,293.00008,"Approximately 144 jurisdictions use IFRS, as ..."
...,...,...,...,...
928,"On December 19, 2019, proceeds from the UKWG a...","In connection with this early retirement, we i...",291,"On December 19, 2019, proceeds from the UKWG a..."
929,unvested restricted stock units such units had...,"At December 31, 2020, there was $7 million of ...",292,"At December 31, 2020, there was $7 million of ..."
930,"In addition, as of March 31, 2018, we adopted ...","As a result of the adoption, we reclassified $...",293,"In addition, as of March 31, 2018, we adopted ..."
931,changes in valuation allowances against state ...,The deferred portion of the state and local ta...,294,The deferred portion of the state and local ta...
932,a change in the valuation allowances against f...,The deferred portion of the foreign taxes incl...,295,The deferred portion of the foreign taxes incl...

In [ ]:
actual_submission[actual_submission['Index']=='0314.00007.1']

,Cause,Effect,Index,Text
40,Though total area of sugarcane increased by 23...,Average sugar price in financial year 2018-19 ...,0314.00007.1,Though total area of sugarcane increased by 2...

In [ ]:
actual_submission[actual_submission['Cause']=='']

Empty DataFrame
Columns: [Cause, Effect, Index,  Text]
Index: []

In [ ]:
actual_submission[actual_submission['Cause']==' ']

Empty DataFrame
Columns: [Cause, Effect, Index,  Text]
Index: []

In [ ]:
actual_submission[actual_submission['Effect']=='']

Empty DataFrame
Columns: [Cause, Effect, Index,  Text]
Index: []

In [ ]:
actual_submission[actual_submission['Effect']==' ']

Empty DataFrame
Columns: [Cause, Effect, Index,  Text]
Index: []

In [ ]:
actual_submission[pd.isnull(actual_submission['Cause'])]

,Cause,Effect,Index,Text
41,NaN,The company plans to pay a 50 per cent dividen...,0314.00007.2,Though total area of sugarcane increased by 2...

In [ ]:
actual_submission[pd.isnull(actual_submission['Effect'])]

,Cause,Effect,Index,Text
40,Though total area of sugarcane increased by 23...,NaN,0314.00007.1,Though total area of sugarcane increased by 2...
100,companies with enterprise value of between $37...,NaN,0350.00028.2,It typically invests between $5 million and $...
167,Liberals Sept. 13: Eliminate the swipe fee me...,NaN,0387.00002.1,Liberals Sept. 13: Eliminate the swipe fee m...
202,"At the beginning of the week, the money market...",NaN,415.00006,"At the beginning of the week, the money marke..."
286,finance minister Nirmala Sitharaman announced ...,NaN,0467.00002.2,"Sensex surges over 2,000 points after governm..."
326,NaN,NaN,0481.00004.2,"The company's largest shareholder, Chinese co..."
368,"Two years into her initial three-year plan, sh...",NaN,0505.00018.1,"Two years into her initial three-year plan, s..."
548,"refining, retailing and marketing operations w...",NaN,0581.00008.2,Elliott said it estimated $22 billion boost t...
583,"the investor lawsuits, Chief Financial Officer...",NaN,0597.00022.2,VW has earmarked 5.5 billion euros in conting...
698,The increase in NuScale costs during 2020 was ...,NaN,60,The increase in NuScale costs during 2020 was ...
742,higher revenues and lower selling and administ...,NaN,105,".Reported EBIT increased 83%, driven by higher..."
811,Revenue growth on a constant currency basis,NaN,174,Revenue growth on a constant currency basis wa...
859,The increase in input costs was driven by high...,NaN,222,The increase in input costs was driven by high...
872,Unfavorable volume/mix was due to the impact o...,NaN,235,Unfavorable volume/mix was due to the impact o...
879,Lower net pricing was driven by biscuits and c...,NaN,242,Lower net pricing was driven by biscuits and c...
895,Business-to-consumer volume increased as the C...,NaN,258,Business-to-consumer volume increased as the C...
917,The increase in cash used was driven by change...,NaN,280,The increase in cash used was driven by change...

In [ ]:
actual_submission.columns

Index(['Cause', 'Effect', 'Index', ' Text'], dtype='object')

In [ ]:
# def null_fill(text, sub_text1, sub_text2):
#   if pd.isnull(sub_text1) and text!=sub_text2:
#     return text.replace(str(sub_text2), '')
#   else:
#     return sub_text1

In [ ]:
# #Extra treatment
# actual_submission['Cause'] = actual_submission.apply(lambda x : null_fill(x[' Text'], x.Cause, x.Effect), axis = 1)
# actual_submission['Effect'] = actual_submission.apply(lambda x : null_fill(x[' Text'], x.Effect, x.Cause), axis = 1)

In [ ]:
actual_submission[pd.isnull(actual_submission['Effect'])]

Empty DataFrame
Columns: [Cause, Effect, Index,  Text]
Index: []

In [ ]:
actual_submission[['Index', ' Text', 'Cause', 'Effect']].to_csv('task2.csv', sep = ';', index = False)

In [ ]:
!zip -r ensemble_effect_only.zip task2.csv

  adding: task2.csv (deflated 83%)

In [ ]:
files.download("pred_finbert_no_pos_test_output.zip")

In [ ]:
pd.read_csv('task2.csv', sep = ';')

,Index,Text,Cause,Effect
0,291.00004,The Israel Tax Authority claims that when a c...,The Israel Tax Authority claims that when a co...,they should have paid 4.3 million shekels in tax.
1,291.00005,"Because Oshrad is a privately held business, ...",Because Oshrad is a privately held business,it was liable for a 26.3% company tax on the s...
2,291.00006,"Instead, the company reported itself as a fam...","Instead, the company reported itself as a fami...",is liable to a single 32% tax.
3,292.00007,"On Tuesday, repo loan rates more than tripled...","On Tuesday, repo loan rates more than tripled","the supply of funds to the banking system, and..."
4,293.00008,"Approximately 144 jurisdictions use IFRS, as ...",it's required for public firms based in South ...,Approximately 144 jurisdictions use IFRS
...,...,...,...,...
928,291,"On December 19, 2019, proceeds from the UKWG a...","On December 19, 2019, proceeds from the UKWG a...","In connection with this early retirement, we i..."
929,292,"At December 31, 2020, there was $7 million of ...",unvested restricted stock units such units had...,"At December 31, 2020, there was $7 million of ..."
930,293,"In addition, as of March 31, 2018, we adopted ...","In addition, as of March 31, 2018, we adopted ...","As a result of the adoption, we reclassified $..."
931,294,The deferred portion of the state and local ta...,changes in valuation allowances against state ...,The deferred portion of the state and local ta...
932,295,The deferred portion of the foreign taxes incl...,a change in the valuation allowances against f...,The deferred portion of the foreign taxes incl...